MySQL:
  driver: "com.mysql.cj.jdbc.Driver" # MySQL 8.0 如果是 MySQL 5.7 请使用 com.mysql.jdbc.Driver
  url: "jdbc:mysql://localhost:3306/your_db" # 数据库地址
  username: "your_username" # 数据库用户名
  password: "your_password" # 数据库密码